services:
  back-end:
    image: andrchr0/sustainability-diary-g2:deploy
    container_name: g2-backend
    restart: unless-stopped
    ports:
      - "8092:8092"
    env_file:
      - .env
    networks:
      - app-network
    deploy:
      update_config:
        order: start-first
    pull_policy: always
  front-end:
    image: andrchr0/sustainability-diary-g2-front-end:deploy
    container_name: g2-frontend
    restart: unless-stopped
    ports:
      - "8082:8082"
    depends_on:
      - back-end
    networks:
      - app-network
    deploy:
      update_config:
        order: start-first
    pull_policy: always

networks:
  app-network:
    driver: bridge