name: CI

on:
  push:
    branches: [ a-component-testing ]
  pull_request:
    branches: [ a-component-testing ]

jobs:
  build-back-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push a docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back-end
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2:latest

  build-front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: build and push a docker image
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2-front-end:latest

  run-tests:
    needs: [build-back-end, build-front-end]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pull and run back-end tests
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2:latest
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2:latest npm test
      - name: Pull and run front-end tests
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2-front-end:latest
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2-front-end:latest npm test
