name: CI

on:
  push:
    branches: [ andreas-testing-branch ]
  pull_request:
    branches: [ andreas-testing-branch ]

jobs:
  test-back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'back-end'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - run: |
          cd back-end
          npm install
          npm test

  build-back-end:
    runs-on: ubuntu-latest
    needs: test-back-end
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'back-end'
      - name: Docker login and build
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back-end
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2:latest

  build-front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - run: npm install
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2-front-end:latest
