name: CI

on:
  push:
    branches: [ andreas-testing-branch ]
  pull_request:
    branches: [ andreas-testing-branch ]

jobs:
  test-back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'back-end'  # Specify the path to the back-end directory
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Change directory to back-end
        run: cd back-end
      - run: npm install
      - run: npm test
      - name: Docker login and build
        uses: docker/build-push-action@v5
        with:
          context: ./back-end
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2:latest

  build-front-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-diary-g2-front-end:latest
